# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# JupyterHub docker-compose configuration file
# run `sudo -E docker-compose up -d` for daemon mode with env vars from the shell
version: "2"

services:
  hub:
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
      args:
        JUPYTERHUB_VERSION: ${JUPYTERHUB_VERSION}
    image: jupyterhub
    container_name: jupyterhub
    volumes:
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      # in form "/path/on/host:/path/on/container"
      - "/home/ubuntu/data:${DATA_VOLUME_CONTAINER}"
    ports:
      # - "443:443"
      - "80:80"
    environment:
      # All containers will join this network
      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}
      # JupyterHub will spawn this Notebook image for users
      DOCKER_NOTEBOOK_IMAGE: ${DOCKER_NOTEBOOK_IMAGE}
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: ${DOCKER_NOTEBOOK_DIR}
      # Data directory inside the user image
      DATA_VOLUME_CONTAINER: ${DATA_VOLUME_CONTAINER}
      # Using this run command (optional)
      DOCKER_SPAWN_CMD: ${DOCKER_SPAWN_CMD}
      AUTH0_SUBDOMAIN: hms-dbmi
      # these should be set in the environment of the machine running Docker
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      AUTH0_CALLBACK_URL: ${AUTH0_CALLBACK_URL}
      S3_ENCRYPT_KEY: ${S3_ENCRYPT_KEY}
      ADMIN_EMAILS: ${ADMIN_EMAILS}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_NOTEBOOK_BUCKET: ${AWS_NOTEBOOK_BUCKET}
      AWS_TEMPLATE_BUCKET: ${AWS_TEMPLATE_BUCKET}
      AWS_RAW_FILE_BUCKET: ${AWS_RAW_FILE_BUCKET}
      AWS_PROC_FILE_BUCKET: ${AWS_PROC_FILE_BUCKET}
      AWS_OPEN_DATA_BUCKET: ${AWS_OPEN_DATA_BUCKET}
      FF_ACCESS_KEY: ""
      FF_ACCESS_SECRET: ""
      INIT_ERR_OUTPUT: ""
      FF_TRACKING_ID: ""

    command:
      - /bin/bash
      - -c
      - |
        wget https://raw.githubusercontent.com/jupyterhub/jupyterhub/${JUPYTERHUB_VERSION}/examples/cull-idle/cull_idle_servers.py
        jupyterhub -f /srv/jupyterhub/jupyterhub_config.py

volumes:
  data:
    external:
      name: ${DATA_VOLUME_HOST}

networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}
